### ISSUE TITLE
Insee v3 endpoints monitoring

### ISSUE THREAD

**Issue by hugolepetit** [etalab/watchdoge_apientreprise#41]
Les tests ne passent plus car différence entre la réalité et les specs sur les endpoints insee v3
```
rspec ./spec/aggregators/dashboard/ping_history_aggregator_spec.rb:24 # Dashboard::PingHistoryAggregator with valid input size should eq 27
rspec ./spec/services/dashboard/current_status_service_spec.rb:26 # Dashboard::CurrentStatusService results contains specifics endpoints names and sub_names
rspec ./spec/services/dashboard/current_status_service_spec.rb:20 # Dashboard::CurrentStatusService results size should equal 27
```

**Comment by Haelle** [comment]
c'est lié à l'API qui récupère les données du Kibana, elle ne renvoie pas les 2 APIs manquantes. Hypothèses : 

- soit c'est filtré dans l'API pour pas les renvoyer (volontaire)
- soit c'est un problème de match de l'URL pour reconnaître l'API (qui est reconnu comme étant l'API normale)

**Comment by Haelle** [comment]
done
